# Generated by Django 3.2.13 on 2024-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_products_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
